document.write('            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" referrerpolicy="no-referrer" />');
document.write('    <!-- Bootstrap CSS -->');
document.write('    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">');
document.write('');
document.write('');
document.write('<div class="container d-block mr-auto ml-auto mt-5" id="container_box_22">');
document.write('<style>');
document.write('@import url(\'https://fonts.googleapis.com/css2?family=Almarai:wght@700&display=swap\');');
document.write('#container_box_22 h2,#container_box_22 h3,#container_box_22 h4,#container_box_22 h5,#container_box_22 h6,#container_box_22 h1,#container_box_22 span,#container_box_22 label,#container_box_22 a,#container_box_22 button,#container_box_22 div,#container_box_22 {');
document.write('    font-family: \'Almarai\', sans-serif;');
document.write('}');
document.write('');
document.write('</style>');
document.write('');
document.write('');
document.write('<style>');
document.write('#container_box_22 #ul {');
document.write('    list-style-type: none;');
document.write('    width: 100%!important;');
document.write('    float: left;');
document.write('    padding-left: 0px;');
document.write('}');
document.write('#container_box_22 #ul li {');
document.write('    float: right;');
document.write('}');
document.write('#container_box_22 .bg-spri {');
document.write('    background: #019ae2;');
document.write('    color: whitesmoke;');
document.write('}');
document.write('#container_box_22 .bg-spr2i-btn-answers {');
document.write('    background: #b8e8ff;');
document.write('    color: #444;');
document.write('}');
document.write('');
document.write('#container_box_22 #ul .li1 span {');
document.write('    padding: 1rem 1rem 1rem 1rem;');
document.write('    border-radius: 50%;');
document.write('}');
document.write('#ul .li2 {');
document.write('    width: calc(100% - 77px);');
document.write('    margin-top: 0px;');
document.write('    margin-right: -1px;');
document.write('}');
document.write('#container_box_22 .list-group-item-action:focus, #container_box_22 .list-group-item-action:hover,#container_box_22 .box:focus,#container_box_22  .box:hover {');
document.write('    z-index: 1;');
document.write('    color: #495057;');
document.write('    text-decoration: none;');
document.write('    background-color: transparent;');
document.write('    outline: none;');
document.write('    cursor:pointer');
document.write('}');
document.write('#container_box_22 .box-answers,.quiz-question,.box-alerts {');
document.write('    display: none;');
document.write('}');
document.write('</style>');
document.write('        <ul id="ul">');
document.write('                <li class="li1">');
document.write('                    <span class="border-circle bg-spri" id="start_number">1</span>');
document.write('                </li>');
document.write('                <li class="li2">');
document.write('                    <div class="progress" style="height: 25px;direction: rtl;background:#019ae2">');
document.write('                    <div class="progress-bar bg-spri" role="progressbar" style="width: 0%;');
document.write('background: linear-gradient( 84deg, #b8e8ff 10%, #38bfff 84%);" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>');
document.write('                    </div>');
document.write('                </li>');
document.write('                <li class="li1" style="position: absolute;');
document.write('    z-index: 20;">');
document.write('                    <span class="border-circle bg-spri" id="end_number">5</span>');
document.write('                </li>');
document.write('        </ul>');
document.write('');
document.write('        <div class="col-md-12 float-right">');
document.write('');
document.write('<center>');
document.write('<button class="btn bg-spri" id="start">بدأ الاختبار</button>');
document.write('');
document.write('</center>');
document.write('<center>');
document.write('                <div class=" quiz-question">');
document.write('                        <h6 class="text-center w-100 mt-2 mb-2 quiz-question-title"></h6>');
document.write('                        <center>  <img class="question-image mt-2 mb-4  quiz-question-image" style="width: 200px;height: 105px;" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/280px-Flag_of_Germany.svg.png">');
document.write('                        </center>  </div>');
document.write('                </center>');
document.write('                <div class=" quiz-answers">');
document.write('                <center>');
document.write('');
document.write('                        <div class="list-group col-md-6  box-answers" theme="1">');
document.write('        <button type="button"  class="list-group-item item-answers text-center answer list-group-item-action bg-spr2i-btn-answers mb-2"> </button>');
document.write('        </div>');
document.write('        </center>');
document.write('');
document.write('');
document.write('<center>');
document.write('        <div class="row box-answers"  theme="2">');
document.write('');
document.write('                <div  class="col-md-6 p-2 item-answers box bg-spr2i-btn-answers answer border-right border-white border-bottom">');
document.write('                    <img class="question-image mt-4 mb-2 d-block mr-auto ml-auto  quiz-answer-image" style="width: 200px;height: 105px;" src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/280px-Flag_of_Germany.svg.png">');
document.write('                    <h6 class="text-center w-100"></h6>');
document.write('                </div>');
document.write('            ');
document.write('        </div>');
document.write('</center>');
document.write('');
document.write('<div class="d-flex justify-content-center" style="display: none!important;" id="loading">');
document.write('  <div class="spinner-border" role="status">');
document.write('    <span class="sr-only">Loading...</span>');
document.write('  </div>');
document.write('</div>');
document.write('');
document.write('<center>');
document.write('    <div class="alert alert-primary w-100 float-right text-center" style="direction:rtl;display:none" id="tqyeem" role="alert">');
document.write('');
document.write('    </div>');
document.write('');
document.write('    <div class="alert alert-success mt-2 float-right w-100" style="display:none" id="tq_box">');
document.write('            <h6 class="text-center">');
document.write('            مرر للاسفل لرؤية إجاباتك');
document.write('</h6>');
document.write('');
document.write('        </div>');
document.write('');
document.write('    <div class="row mt-2">');
document.write('        <div class="col-md-12" style="direction:rtl;display:none" id="results_box">');
document.write('            <h4 class="text-center">هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.');
document.write('</h4>');
document.write('<img src="https://damaspost.com/wp-content/uploads/2019/08/67977575_405844390280325_6270331903434293248_n.jpg" style="width:60%!important" class=" mr-auto ml-auto">');
document.write('        </div>');
document.write('    </div>');
document.write('');
document.write('    <div class="row mt-2" id="sharebox" style="display:none">');
document.write('        <div class="d-flex justify-content-center w-100" style="direction:rtl;">');
document.write('<ul class="" style="list-style-type:none">');
document.write('<li class="float-left mr-3"><a href="" id="whatsapp" class="btn btn-success"><i class="fa fa-whatsapp"></i> مشاركة</a></li>');
document.write('<li class="float-left"><a href="" id="facebook" class="btn btn-primary"><i class="fa fa-facebook"></i> مشاركة</a></li>');
document.write('');
document.write('</ul>');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('        </div>');
document.write('        <div class="d-flex justify-content-center w-100" style="direction:rtl;">');
document.write('');
document.write('        <ul class="" style="list-style-type:none">');
document.write('<li class="float-left"><a onclick="location.reload()" class="btn text-white btn-primary"><i class="fa fa-refresh"></i> إعادة الإختبار</a></li>');
document.write('');
document.write('</ul>');
document.write('</div>');
document.write('    </div>');
document.write('');
document.write('    <div class="alert alert-success mt-2" style="display:none" id="award_box">');
document.write('        <div class="col-md-12" style="direction:rtl;">');
document.write('<h1 class="text-center w-100" style="font-size: 7rem;"><i class="fa fa-trophy"></i></h1>');
document.write('            <h4 class="text-center">هذا النص هو مثال لنص يمكن أن يستبدل في نفس المساحة، لقد تم توليد هذا النص من مولد النص العربى، حيث يمكنك أن تولد مثل هذا النص أو العديد من النصوص الأخرى إضافة إلى زيادة عدد الحروف التى يولدها التطبيق.');
document.write('</h4>');
document.write('<a href="">asasdas</a>');
document.write('        </div>');
document.write('    </div>');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('        <div class="row box-alerts mt-3">');
document.write('      ');
document.write('        <h2 class="text-center w-100 float-right">الاسئلة مع الاجوبة</h2>');
document.write('        <div class="alert  w-100 float-right text-right" role="alert">');
document.write('     ');
document.write('        <div class="h2 w-100 float-right"><div class="media" style="direction: rtl;">');
document.write('');
document.write('');
document.write('<img src="https://via.placeholder.com/150" class="" style="width: 200px;height: 105px;" alt="...">');
document.write('');
document.write('  <div class="media-body">');
document.write('    <h4 class="mt-4 ml-3">Media heading</h4>');
document.write('  </div>');
document.write('</div>');
document.write('</div>');
document.write('        <div class="h4 w-100 float-right"><div class="media" style="direction: rtl;">');
document.write('  <img src="https://via.placeholder.com/150" class="ml-3" style="width: 200px;height: 105px;" alt="...">');
document.write('  <div class="media-body">');
document.write('    <h5 class="mt-4">Media heading</h5>');
document.write('  </div>');
document.write('</div>');
document.write('');
document.write('');
document.write('');
document.write('</div>');
document.write('        </div>');
document.write('            ');
document.write('        </div>');
document.write('</center>');
document.write('');
document.write('                </div>');
document.write('');
document.write('           ');
document.write('           ');
document.write('');
document.write('        </div>');
document.write('</div>');
document.write('    <!-- Optional JavaScript -->');
document.write('    <!-- jQuery first, then Popper.js, then Bootstrap JS -->');
document.write('    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>');
document.write('        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>');
document.write('    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>');
document.write('');
